#define ERR -1

#define VOID 1
#define INT 2
#define DOUBLE 3
#define BOOL 4
#define STRING 5
#define CLASS 6
#define INTERFACE 7
#define NULL 8
#define THIS 9
#define EXTEND 10
#define IMPLEMENTS 11
#define FOR 12
#define WHILE 13
#define IF 14
#define ELSE 15
#define RETURN 16
#define BREAK 17
#define CONTINUE 18
#define NEW 19
#define NEWARRAY 20
#define PRINT 21
#define READINTEGER 22
#define READLINE 23
#define DTOI 24
#define ITOD 25
#define BTOI 26
#define ITOB 27
#define PRIVATE 28
#define PROTECTED 29
#define PUBLIC 30

#define IDENTIFIER 31
#define PLUS 32
#define MINUS 33
#define STAR 34
#define SLASH 35
#define PERCENT 36