#define VOID 1
#define INT 2
#define DOUBLE 3
#define BOOL 4
#define STRING 5
#define CLASS 6
#define INTERFACE 7
#define NULL 8
#define THIS 9
#define EXTEND 10
#define IMPLEMENTS 11
#define FOR 12
#define WHILE 13
#define IF 14
#define ELSE 15
#define RETURN 16
#define RETURN 17
#define BREAK 18
#define CONTINUE 19
#define NEW 20
#define NEWaRRAY 21
#define PRINT 22
#define READINTEGER 23
#define READLINE 24
#define DTOI 25
#define ITOD 26
#define BTOI 27
#define ITOB 28
#define PRIVATE 29
#define PROTECTED 30
#define PUBLIC 31